apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: quarkus-github-artifactory
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: artifactory-docker-artifactory-jcr.apps.rosa.rhtap-services.xmdt.p3.openshiftapps.com/rhtap/raisa-test:bf63fc5ebd972dcc74d32a21e5c2eeea1671a98a@sha256:19f53e386af5198fff22c8e1b63161a259e8d818a43a849e76e1474fb8cc69c5
          name: container-image
